//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lardite.RefAssistant {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lardite.RefAssistant.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception occurs during checking of XAML(BAML) types..
        /// </summary>
        internal static string BamlTypesChecker_CheckTypeException {
            get {
                return ResourceManager.GetString("BamlTypesChecker_CheckTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception occurs during analysing of type &apos;{0}&apos;. See Inner exception for more details..
        /// </summary>
        internal static string CheckTypeException_Message {
            get {
                return ResourceManager.GetString("CheckTypeException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception occurs during checking of interop type &apos;{0}&apos;..
        /// </summary>
        internal static string CleanExecutor_CheckInteropTypeException {
            get {
                return ResourceManager.GetString("CleanExecutor_CheckInteropTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception occurs during checking of attributes of type &apos;{0}&apos;..
        /// </summary>
        internal static string CleanExecutor_CheckTypeAttributesException {
            get {
                return ResourceManager.GetString("CleanExecutor_CheckTypeAttributesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception occurs during checking of hierarchy of type &apos;{0}&apos;..
        /// </summary>
        internal static string CleanExecutor_CheckTypeHierarchyException {
            get {
                return ResourceManager.GetString("CleanExecutor_CheckTypeHierarchyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception occurs during checking of interfaces of type &apos;{0}&apos;..
        /// </summary>
        internal static string CleanExecutor_CheckTypeInterfacesException {
            get {
                return ResourceManager.GetString("CleanExecutor_CheckTypeInterfacesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; can not be an empty string..
        /// </summary>
        internal static string Error_ArgumentEmpty {
            get {
                return ResourceManager.GetString("Error_ArgumentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified argument was out of the range of valid values..
        /// </summary>
        internal static string Error_ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("Error_ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get active project..
        /// </summary>
        internal static string ExtensionManager_CannotGetActiveProject {
            get {
                return ResourceManager.GetString("ExtensionManager_CannotGetActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========== Remove: succeeded, {0} reference(s) removed ==========.
        /// </summary>
        internal static string ExtensionManager_EndProcess {
            get {
                return ResourceManager.GetString("ExtensionManager_EndProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========== Remove: unused references are not found ==========.
        /// </summary>
        internal static string ExtensionManager_EndProcessWithoutReferences {
            get {
                return ResourceManager.GetString("ExtensionManager_EndProcessWithoutReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting unused references.
        /// </summary>
        internal static string ExtensionManager_GettingUnusedReferences {
            get {
                return ResourceManager.GetString("ExtensionManager_GettingUnusedReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project&apos;s output is not CLR assembly. Reference Assistant cannot be  used for this project type..
        /// </summary>
        internal static string ExtensionManager_IsNotClrAssembly {
            get {
                return ResourceManager.GetString("ExtensionManager_IsNotClrAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ExtensionManager_RemoveReady {
            get {
                return ResourceManager.GetString("ExtensionManager_RemoveReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing unused references.
        /// </summary>
        internal static string ExtensionManager_RemovingUnusedReferences {
            get {
                return ResourceManager.GetString("ExtensionManager_RemovingUnusedReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing unused usings.
        /// </summary>
        internal static string ExtensionManager_RemovingUnusedUsings {
            get {
                return ResourceManager.GetString("ExtensionManager_RemovingUnusedUsings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------ Remove Unused References started: Project: {0}, Configuration: {1} {2} ------.
        /// </summary>
        internal static string ExtensionManager_StartProcess {
            get {
                return ResourceManager.GetString("ExtensionManager_StartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========== Remove: user cancelled operation ==========.
        /// </summary>
        internal static string ExtensionManager_UserCancelledOperation {
            get {
                return ResourceManager.GetString("ExtensionManager_UserCancelledOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result for project &apos;{0}&apos; is already added..
        /// </summary>
        internal static string InspectResult_ResultAlreadyAdded {
            get {
                return ResourceManager.GetString("InspectResult_ResultAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception occurs during checking parameters of a member &apos;{0}&apos; from a module &apos;{1}&apos;..
        /// </summary>
        internal static string MemberReferencesCheckHelper_CheckMemberReferenceException {
            get {
                return ResourceManager.GetString("MemberReferencesCheckHelper_CheckMemberReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception occurs during checking overloaded methods &apos;{0}&apos; (having {1} parameter(s)) from a module &apos;{2}&apos;..
        /// </summary>
        internal static string MemberReferencesCheckHelper_CheckOverloadedMethodsException {
            get {
                return ResourceManager.GetString("MemberReferencesCheckHelper_CheckOverloadedMethodsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception occurs during checking of referenced methods of type &apos;{0}&apos;..
        /// </summary>
        internal static string MemberReferencesCheckHelper_CheckTypeException {
            get {
                return ResourceManager.GetString("MemberReferencesCheckHelper_CheckTypeException", resourceCulture);
            }
        }
    }
}
